name: gphoton
channels:
  - numba
  - conda-forge
dependencies:
  - python>=3.10
  - astropy
  - dustgoggles
  - fast-histogram
  - fitsio
  - more-itertools
  - matplotlib
  - numba
  - numpy>=2.2
  - pandas
  - photutils>=2.0
  - pip
  - pyarrow
  - requests
  - rich
  - rasterio
  - scikit-image>=0.20
  - scikit-learn
  - scipy
  - sh
  - shapely
  # optional, used in pipeline CLI
  - fire
  # optional, used for some gzip-handling features
  - python-isal
  # non-mandatory, some performance improvements to numba --
  # cannot be used on non-x64 platforms
  - icc_rt
  # optional, only required for object-search functions
  - astroquery
  # optional, only required for tests
  - pytest
  - quickbin
